// <auto-generated />
namespace PharrellAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class regionhasmanysentiments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(regionhasmanysentiments));
        
        string IMigrationMetadata.Id
        {
            get { return "201505280915380_region-has-many-sentiments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
