// <auto-generated />
namespace PharrellAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class tweet_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tweet_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201505270336422_tweet_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
