// <auto-generated />
namespace PharrellAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Having_a_go : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Having_a_go));
        
        string IMigrationMetadata.Id
        {
            get { return "201505270813038_Having_a_go"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
